resolver: lts-9.1
packages:
  - '.'
  - location:
      git: https://github.com/Soostone/safecopy-hunit.git
      commit: c573e756a2057034c9b33b0509af15fa54eeb246
    extra-dep: true
extra-deps:
  - path-0.6.1
  - path-io-1.3.3
flags:
  instrument:
    lib-Werror: true
extra-package-dbs: []
