resolver: lts-14.0
packages:
  - instrument
  - instrument-cloudwatch
extra-deps:
  - amazonka-1.6.1
  - amazonka-cloudwatch-1.6.1
  - amazonka-core-1.6.1
  - http-client-0.5.14
  - csv-conduit-0.7.0.0
  - git: https://github.com/Soostone/safecopy-hunit.git
    commit: c573e756a2057034c9b33b0509af15fa54eeb246
flags:
  instrument:
    lib-Werror: true
  instrument-cloudwatch:
    lib-Werror: true
extra-package-dbs: []
