resolver: lts-18.10
packages:
  - instrument
  - instrument-cloudwatch
extra-deps:
  - git: https://github.com/brendanhay/amazonka.git
    commit: 23495aaf7f08d6666f8e3bc8e72f5041ce7c6801
    subdirs:
      - amazonka
      - amazonka-cloudwatch
  - csv-conduit-0.7.3.0
  - git: https://github.com/Soostone/safecopy-hunit.git
    commit: c573e756a2057034c9b33b0509af15fa54eeb246

flags:
  instrument:
    lib-Werror: true
  instrument-cloudwatch:
    lib-Werror: true
extra-package-dbs: []
